# Generated by Django 5.0.3 on 2024-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
